name: Deploy Backend to ECS

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Build & Push Backend Image
      - name: Build and Push Backend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: ${{ secrets.ECR_REPOSITORY_BACKEND }}
          IMAGE_TAG: docker tag backend-user-app:latest 619576923139.dkr.ecr.ap-south-1.amazonaws.com/backend-user-app:latest
        run: |
          IMAGE=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
          echo "Building image: $IMAGE"

          docker build -t backend-user-app .
          docker push 619576923139.dkr.ecr.ap-south-1.amazonaws.com/backend-user-app:latest

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # 5️⃣ Render ECS Task Definition (ONLY image update)
      - name: Render Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ secrets.ECS_TASK_DEFINITION_BACKEND }}
          container-name: ${{ secrets.CONTAINER_NAME_BACKEND }}
          image: ${{ env.IMAGE }}

      # 6️⃣ Deploy to ECS Fargate
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ secrets.ECS_CLUSTER }}
          service: ${{ secrets.ECS_SERVICE_BACKEND }}
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          wait-for-service-stability: true
